# Generated by Django 5.1.4 on 2024-12-30 03:08

import picklefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, null=True)),
                ('error', models.TextField()),
                ('error_function', models.TextField(db_index=True)),
                ('request_payload', picklefield.fields.PickledObjectField(editable=False)),
            ],
            options={
                'db_table': 'error_log',
            },
        ),
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, null=True)),
                ('session_key', models.TextField(db_index=True)),
                ('session_type', models.TextField(db_index=True)),
                ('session_data', picklefield.fields.PickledObjectField(editable=False)),
            ],
            options={
                'db_table': 'session_data',
            },
        ),
    ]
